# Generated by Django 5.0.2 on 2024-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=20)),
                ('localidad', models.CharField(blank=True, max_length=20, null=True)),
                ('descripción', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
